name: ubuntu18.04 arm64 v10.0.0 build
run-name: ubuntu18 arm64

on:
  push:
    branches:
      - v10.0.0

jobs:
  build-arm64-ubuntu18:
    runs-on: ubuntu-24.04-arm
    container:
      # dockerhub镜像
      image: docker://ubuntu:18.04

    steps:
      - name: Check out repository code
        uses: actions/checkout@v1 # https://github.com/actions/checkout/issues/1590
        with:
          fetch-depth: 1
      
      - name: Install
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          apt update
          apt install -y sudo lsb-release git wget libcurl4-openssl-dev pkg-config g++ cmake uuid-dev libncurses5-dev python3-dev autoconf automake libtool libeigen3-dev libtiff-dev libsqlite3-dev sqlite3

      - name: Build
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
            echo "-----------------------"
            uname -a
            lsb_release -a
            echo "-----------------------"
            bash -c "python3 install.py && source install/setup.bash && mkdir -p build && cd build && cmake .. && make -j$(nproc)"
