name: manually arm64 ubuntu20.04 v10.0.0 build
run-name: manually ubuntu20 arm64

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
      tags:
        description: "Test scenario tags"

jobs:
  build-arm64-ubuntu20:
    runs-on: ubuntu-24.04-arm
    container:
      # dockerhub镜像
      image: docker://ubuntu:20.04

    steps:
      - name: Check out repository code
        uses: actions/checkout@v1 # https://github.com/actions/checkout/issues/1590
        with:
          fetch-depth: 1

      - name: Install
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          apt update
          apt install -y sudo lsb-release git wget libcurl4-openssl-dev pkg-config g++ cmake uuid-dev libncurses5-dev python3-dev autoconf automake libtool libeigen3-dev libtiff-dev libsqlite3-dev sqlite3

      - name: Build
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          echo "-----------------------"
          uname -a
          lsb_release -a
          echo "-----------------------"
          echo "Log level: ${{ github.event.inputs.logLevel }}"
          echo "Tags: ${{ github.event.inputs.tags }}"
          echo "Inputs: ${{ toJson(github.event.inputs) }}"
          bash -c "python3 install.py && source install/setup.bash && mkdir -p build && cd build && cmake .. && make -j$(nproc)"
