name: ubuntu22.04 v9.0.0 build arrch64
run-name: ubuntu22 arrch64

on:
  push:
    branches:
      - v9.0.0

jobs:
  build-arm-ubuntu22:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        env:
          DEBIAN_FRONTEND: noninteractive
        id: runcmd
        with:
          arch: aarch64
          distro: ubuntu22.04

          install: |
            apt update
            apt install -y lsb-release git wget pkg-config g++ cmake uuid-dev libncurses5-dev python3-dev

          run: |
            echo "-----------------------"
            uname -a
            lsb_release -a
            echo "-----------------------"
            bash -c "python3 install.py && source install/setup.bash && mkdir -p build && cd build && cmake .. && make -j$(nproc)"
