name: ubuntu18.04 v9.0.0 build arrch64
run-name: ubuntu18 arrch64

on:
  push:
    branches:
      - v9.0.0

jobs:
  build-arm-ubuntu18:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v1 # https://github.com/actions/checkout/issues/1590
        with:
          fetch-depth: 1

      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        env:
          DEBIAN_FRONTEND: noninteractive
        id: runcmd
        with:
          arch: aarch64
          distro: ubuntu18.04

          install: |
            apt update
            apt install -y lsb-release git wget pkg-config g++ cmake uuid-dev libncurses5-dev python3-dev

          run: |
            echo "-----------------------"
            uname -a
            lsb_release -a
            echo "-----------------------"
            bash -c "python3 install.py && source install/setup.bash && mkdir -p build && cd build && cmake .. && make -j$(nproc)"
