name: ubuntu-latest v8.0.0 build
run-name: CyberRT v8.0.0 build runner on ubuntu latest 🚀

on:
  pull_request:
    branches:
      - master
  push:
    paths:
      - 'cmake/**'
      - 'cyber/**'
      - 'modules/**'
      - 'CMakeLists.txt'
      - 'scripts/**'
      - '.github/workflows/ubuntu-latest-v8.0.0-build.yaml'

jobs:
  build-amd-ubuntu22:
    runs-on: ubuntu-latest
    container:
      image: docker://ubuntu:latest
      options: --volume ${{ github.workspace }}:/workspace/${{ github.repository }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          apt update
          apt install -y git wget pkg-config g++ cmake libpoco-dev uuid-dev libncurses5-dev python3-dev
          cd /workspace/${{ github.repository }} && ./scripts/install.sh
      - name: Build
        run: |
          bash -c "cd /workspace/${{ github.repository }} && source install/setup.bash && mkdir -p build && cd build && cmake .. && make -j$(nproc)"
