name: ubuntu-latest v9.0.0 build x86-64
run-name: ubuntu latest x86-64

on:
  push:
    branches:
      - v9.0.0

jobs:
  build-amd-ubuntu-latest:
    runs-on: ubuntu-latest
    container:
      image: docker://ubuntu:latest
      options: --volume ${{ github.workspace }}:/workspace/${{ github.repository }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          apt update
          apt install -y lsb-release git wget pkg-config g++ cmake uuid-dev libncurses5-dev python3-dev
          cd /workspace/${{ github.repository }} && python3 install.py

      - name: Build
        run: |
          echo "-----------------------"
          uname -a
          lsb_release -a
          echo "-----------------------"
          bash -c "cd /workspace/${{ github.repository }} && source install/setup.bash && mkdir -p build && cd build && cmake .. && make -j$(nproc)"
