name: ubuntu20.04 v8.0.0 build arrch64
run-name: CyberRT v8.0.0 build runner on ubuntu20 arrch64 🚀

on:
  push:
    branches:
      - v8.0.0

jobs:
  build-arm-ubuntu20:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        env:
          DEBIAN_FRONTEND: noninteractive
        id: runcmd
        with:
          arch: aarch64
          distro: ubuntu20.04

          install: |
            apt update
            apt install -y lsb-release git wget pkg-config g++ cmake libpoco-dev uuid-dev libncurses5-dev python3-dev
            git clone --depth 1 --single-branch --branch v8.0.0 https://github.com/minhanghuang/CyberRT.git /root/workspace

          run: |
            echo "-----------------------"
            uname -a
            lsb_release -a
            echo "-----------------------"
            cd /root/workspace && ./scripts/install.sh
            bash -c "cd /root/workspace && source install/setup.bash && mkdir -p build && cd build && cmake .. && make -j$(nproc)"

