name: ubuntu-latest v9.0.0 build x86-64
run-name: CyberRT v9.0.0 build runner on ubuntu latest x86-64🚀

on:
  push:
    paths:
      - '.github/workflows/ubuntu-latest-v9.0.0-build.yaml'

  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  build-amd-ubuntu-latest:
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    container:
      image: docker://ubuntu:latest
      options: --volume ${{ github.workspace }}:/workspace/${{ github.repository }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          apt update
          apt install -y lsb-release git wget pkg-config g++ cmake libpoco-dev uuid-dev libncurses5-dev python3-dev
          cd /workspace/${{ github.repository }} && python3 install.py

      - name: Build
        run: |
          echo "-----------------------"
          uname -a
          lsb_release -a
          echo "-----------------------"
          bash -c "cd /workspace/${{ github.repository }} && source install/setup.bash && mkdir -p build && cd build && cmake .. && make -j$(nproc)"
